spring.application.name=nyumba-server

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/nyumba_db
spring.datasource.username=postgres
spring.datasource.password=madtitan634
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=O3X0Z3Ph5WvqV2e6/GXPjK2dtJsVohXHjzvIMYn8F/dvWXVnX3wg/lGsbULRAg8f
Tq0PFRIdFZukIY2qjbtriQ==
jwt.expiration=86400000

# Server port
server.port=8080